# Generated by Django 5.1.6 on 2025-02-22 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('activity_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('organizer', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('ticket_price', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'theme_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ImportDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField()),
                ('timezone_type', models.IntegerField()),
                ('timezone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'theme_import_dates',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_timestamp', models.DateTimeField(blank=True, null=True)),
                ('limit_count', models.IntegerField(blank=True, null=True)),
                ('offset_count', models.IntegerField(blank=True, null=True)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '查詢結果',
                'verbose_name_plural': '查詢結果',
                'db_table': 'theme_query_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QueryEventRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme_entertainment.events')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme_entertainment.queryresult')),
            ],
            options={
                'db_table': 'theme_query_event_relations',
                'managed': True,
            },
        ),
    ]
