# Generated by Django 5.1.6 on 2025-02-22 20:56

import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel/', verbose_name='圖片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('url', models.URLField(blank=True, null=True, verbose_name='連結')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '輪播圖',
                'verbose_name_plural': '輪播圖',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分類名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分類描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '討論區分類',
                'verbose_name_plural': '討論區分類',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='評論內容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='評論時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
            ],
            options={
                'verbose_name': '評論',
                'verbose_name_plural': '評論',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '精選文章',
                'verbose_name_plural': '精選文章',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='內容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='瀏覽次數')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='允許評論')),
                ('is_published', models.BooleanField(default=True, verbose_name='是否發布')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='發布時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否刪除')),
            ],
            options={
                'verbose_name': '討論文章',
                'verbose_name_plural': '討論文章',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='圖片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='價格')),
                ('ranking', models.IntegerField(default=0, verbose_name='排名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '產品排名',
                'verbose_name_plural': '產品排名',
                'ordering': ['ranking', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='收藏時間')),
            ],
            options={
                'verbose_name': '收藏文章',
                'verbose_name_plural': '收藏文章',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='標籤名稱')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='標籤圖標')),
                ('description', models.TextField(blank=True, verbose_name='標籤描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
