# Generated by Django 5.1.6 on 2025-02-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_system', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='forum_system_comment',
        ),
    ]
