# Generated by Django 5.1.6 on 2025-02-19 10:09

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_category_post_is_deleted_post_likes_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='描述'),
        ),
    ]
